export const APP_TITLE = "Nifty50 Live";
export const REFRESH_INTERVAL_MS = 60000; // 1 minute
export const NIFTY_INDEX_SYMBOL = "NSE:NIFTY50-INDEX";

// Top Nifty 50 Symbols mapped to Fyers Symbol Format
export const NIFTY50_SYMBOLS = [
  "NSE:RELIANCE-EQ", "NSE:HDFCBANK-EQ", "NSE:ICICIBANK-EQ", "NSE:INFY-EQ", "NSE:ITC-EQ",
  "NSE:TCS-EQ", "NSE:LTIM-EQ", "NSE:KOTAKBANK-EQ", "NSE:LT-EQ", "NSE:AXISBANK-EQ",
  "NSE:SBIN-EQ", "NSE:BHARTIARTL-EQ", "NSE:BAJFINANCE-EQ", "NSE:ASIANPAINT-EQ", "NSE:MARUTI-EQ",
  "NSE:HCLTECH-EQ", "NSE:SUNPHARMA-EQ", "NSE:TITAN-EQ", "NSE:ULTRACEMCO-EQ", "NSE:TATASTEEL-EQ",
  "NSE:NTPC-EQ", "NSE:POWERGRID-EQ", "NSE:TATAMOTORS-EQ", "NSE:INDUSINDBK-EQ", "NSE:HINDUNILVR-EQ",
  "NSE:NESTLEIND-EQ", "NSE:GRASIM-EQ", "NSE:JSWSTEEL-EQ", "NSE:ADANIENT-EQ", "NSE:ADANIPORTS-EQ",
  "NSE:CIPLA-EQ", "NSE:WIPRO-EQ", "NSE:TECHM-EQ", "NSE:ONGC-EQ", "NSE:SBILIFE-EQ",
  "NSE:DRREDDY-EQ", "NSE:BRITANNIA-EQ", "NSE:COALINDIA-EQ", "NSE:TATACONSUM-EQ", "NSE:EICHERMOT-EQ",
  "NSE:BAJAJ-AUTO-EQ", "NSE:DIVISLAB-EQ", "NSE:APOLLOHOSP-EQ", "NSE:HDFCLIFE-EQ", "NSE:BAJAJFINSV-EQ",
  "NSE:BPCL-EQ", "NSE:HEROMOTOCO-EQ", "NSE:UPL-EQ", "NSE:M&M-EQ"
];

// Approximate Weightage in Nifty 50 (As of recent data, normalized to 100 for calculation)
// Key: Symbol Suffix (e.g. RELIANCE)
export const NIFTY_WEIGHTAGE: Record<string, number> = {
  "HDFCBANK": 13.52,
  "RELIANCE": 9.81,
  "ICICIBANK": 7.85,
  "INFY": 5.86,
  "LTIM": 0.53, // Adjusted
  "ITC": 4.45,
  "TCS": 3.96,
  "LT": 3.65,
  "AXISBANK": 3.25,
  "SBIN": 3.05,
  "BHARTIARTL": 2.95,
  "BAJFINANCE": 2.35,
  "KOTAKBANK": 2.85,
  "HINDUNILVR": 2.30,
  "M&M": 1.95,
  "TATAMOTORS": 1.75,
  "MARUTI": 1.65,
  "SUNPHARMA": 1.55,
  "TITAN": 1.45,
  "NTPC": 1.35,
  "TATASTEEL": 1.30,
  "ULTRACEMCO": 1.15,
  "POWERGRID": 1.10,
  "ADANIENT": 1.05,
  "INDUSINDBK": 0.95,
  "HCLTECH": 0.90,
  "NESTLEIND": 0.90,
  "ONGC": 0.85,
  "JSWSTEEL": 0.80,
  "ADANIPORTS": 0.80,
  "GRASIM": 0.75,
  "COALINDIA": 0.70,
  "SBILIFE": 0.70,
  "BAJAJ-AUTO": 0.65,
  "DRREDDY": 0.65,
  "CIPLA": 0.65,
  "WIPRO": 0.60,
  "HDFCLIFE": 0.60,
  "BRITANNIA": 0.55,
  "TECHM": 0.55,
  "TATACONSUM": 0.55,
  "EICHERMOT": 0.50,
  "BAJAJFINSV": 0.50,
  "DIVISLAB": 0.45,
  "APOLLOHOSP": 0.45,
  "BPCL": 0.45,
  "HEROMOTOCO": 0.40,
  "ASIANPAINT": 1.45, // Correction
  "UPL": 0.35,
  // Add fallback/others to ensure non-zero
};